Feat: deploy scripts and deploy contracts to Mode and Optimism
metastable-labs/contracts pull request #1
Opened 2024-04-25 14:09 UTC by codebuster22

2024-04-25 16:10 UTC, njokuScript commented on .env.example
> +L2_BRIDGE_ADDRESS=0x4200000000000000000000000000000000000010
is this same across the superchain?

2024-04-25 16:11 UTC, njokuScript commented on README.md
> +## SuperMigrate
Supermigrate

2024-04-25 16:13 UTC, njokuScript commented on src/migration/factory/BasedERC20Factory.sol
>   * @notice Factory contract for creating and deploying BasedMigrateERC20 tokens.
can we change `BasedMigrateERC20` to `SupermigrateERC20`? This way we're not just agnostic to Base but to all L2s

2024-04-25 16:13 UTC, njokuScript requested changes
Look at the comments I left @codebuster22 

Great work, btw!

2024-04-27 18:34 UTC, codebuster22 commented on .env.example
> +L2_BRIDGE_ADDRESS=0x4200000000000000000000000000000000000010
Yes, Though, scroll is not part of Optimism Super Chain.

2024-04-27 18:34 UTC, codebuster22 commented on README.md
> +## SuperMigrate
cool.

2024-04-27 18:35 UTC, codebuster22 commented on src/migration/factory/BasedERC20Factory.sol
>   * @notice Factory contract for creating and deploying BasedMigrateERC20 tokens.
Yes, makes sense.

2024-04-27 23:59 UTC, njokuScript approved these changes

2024-04-27 23:59 UTC, merged